baseURL = "https://de.shoogle.net/bayern"
languageCode = "de-DE"
title = "Bayern"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "bayern"
